name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v5

      # 2️⃣ Setup Node
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5️⃣ Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}

      # 6️⃣ Install Java for Allure
      - name: Install Java (for Allure)
        run: |
          apt-get update
          apt-get install -y openjdk-11-jdk
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

      # 7️⃣ Install Allure CLI
      - name: Install Allure Commandline
        run: npm install -g allure-commandline --save-dev

      # 8️⃣ Generate Allure Report
      - name: Generate Allure Report
        run: allure generate ./allure-results -o ./allure-report --clean

      # 9️⃣ Upload Allure Report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30